### ISSUE TITLE
Cytomappershiny - Error: Graphics API version mismatch

### ISSUE THREAD

**Issue by jparkinson375** [BodenmillerGroup/cytomapper#65] opened 2022-08-15 17:48 UTC
Hi, apologies if this is duplicated somewhere else, but I couldn't find anything about it in the past issues.

I have used the Steinbock analysis pipeline and am now using Cytomapper (version 1.8.0) to analyse the data. When I try to run Cytomappershiny, the GUI loads and I can load and view images/channels in the first "Scatterplot" tab. However, in the "Images" tab I get the error: Graphics API version mismatch in the expression section and nothing appears in the right section.

When I close back to R I get the following information.

![image](https://user-images.githubusercontent.com/37408565/184687900-d39af48d-a84a-489f-8f43-5fb6b8a22387.png)

Any idea what could be causing this?

Many thanks.

**Comment by nilseling** [comment] 2022-08-16 08:04
Hi @jparkinson375,

could you please post the output of `sessionInfo()` here and the function call that you used to open the shiny app. The warning can be ignored for now.

**Comment by jparkinson375** [comment] 2022-08-16 10:06
Thanks for the speedy reply nilseling,

Here is the output of sessionInfo()

![image](https://user-images.githubusercontent.com/37408565/184853298-c45919af-f001-460c-a735-5950e5e0bc73.png)

I am using this code to open the app:

`if (interactive()) {
    
    images <- readRDS("./images.rds")
    masks <- readRDS("./masks.rds")
    
    cytomapperShiny(object = spe, mask = masks, image = images, 
                    cell_id = "ObjectNumber", img_id = "sample_id")
}`

From your guide here: https://bodenmillergroup.github.io/IMCDataAnalysis/cell-phenotyping.html#classification

**Comment by nilseling** [comment] 2022-08-16 10:40
Thanks! Unfortunately I can't reproduce the error on my side. Would it be possible if you send me the spe object of a single image as well as the matching multi-channel image and segmentation mask as CytoImageList object via mail: nils.eling@uzh.ch.

**Comment by jparkinson375** [comment] 2022-08-16 12:59
Thanks, I have just emailed the data to you.

**Comment by nilseling** [comment] 2022-08-16 14:59
Hi @jparkinson375,

thanks for sending the data! I was not able to reproduce the error on my side. But I have only loaded `cytomapper` v1.9.1 and no other packages. So I'm assuming there is a function clash with another package that you have loaded. Could you please try to run the command only when loading `cytomapper`?

**Comment by jparkinson375** [comment] 2022-08-17 14:40
No problem at all.

I tried starting a completely fresh instance of Rstudio and loading only Cytomapper and the required data, I even tried running it in R (4.2.1) without using Rstudio and I still get the same error. I was able to get some more info on the error though, I am not sure if this is any help.

![image](https://user-images.githubusercontent.com/37408565/185162928-aa4fc71b-4b68-4f4f-ae81-10fd48493701.png)

This is what my sessionInfo() outputs when I only load cytomapper, does this look right, is any package being loaded that isn't on your machine?

![image](https://user-images.githubusercontent.com/37408565/185165253-5c2fc917-ae56-46f2-98c3-082619b98469.png)

**Comment by nilseling** [comment] 2022-08-17 14:46
Hmm, so the issue is really the graphics device. Would `install.packages("svglite", type = "source")` (reinstalling `svglite`) solve the issue?

**Comment by jparkinson375** [comment] 2022-08-17 15:01
That worked! It seems to be working normally now.

Thank you for all the help.

**Comment by nilseling** [comment] 2022-08-17 15:12
That's great :) closing now

**Closed by nilseling** 2022-08-17 15:12 UTC
